### ISSUE TITLE
Too many open files errors

### ISSUE THREAD

**Issue by mymasse** [thomasmmitchell/doomsday#12]
Running Doomsday with the Bosh release (v0.6.1) and after a while it just stops working. Looking in the logs it starts reporting `socket: too many open files` for all backends. We only use the `credhub` and the `tlsclient` backends, but the error is reported for both. The dashboard also becomes unavailable.

**Comment by thomasmitchell** [comment]
Hm. One of those scrapers probably leaks their connection, then. Will definitely investigate.

**Comment by thomasmitchell** [comment]
Looks like this is happening because the calls to renew the UAA token aren't closing the response body from the HTTP request. The connection gets closed, but the file descriptor is left around, and eventually we run up against ulimits. Easy to fix. Will be in the next release, which I will attempt to get out soon

**Comment by thomasmitchell** [comment]
Fixed in 2c38ea65683911021e84abe1acfc7b3a8078fe1b

**Comment by mymasse** [comment]
Wow that was fast

**Comment by thomasmitchell** [comment]
Released in v0.8.0
